models/Category.php
<?php

namespace app\models;

use Yii;

/**
 * This is the model class for table "category".
 *
 * @property int $id
 * @property int $parent_id
 * @property string $name
 * @property string $keywords
 * @property string $description
 */
class Category extends \yii\db\ActiveRecord
{
    /**
     * @inheritdoc
     */
    public static function tableName()
    {
        return 'category';
    }
    
    public function getProduct() {
        return $this->hasMany(Product::className(), ['category_id' => 'id']);
    }

    /**
     * @inheritdoc
     */
    public function rules()
    {
        return [
            [['parent_id'], 'integer'],
            [['name'], 'required'],
            [['name', 'keywords', 'description'], 'string', 'max' => 255],
        ];
    }

    /**
     * @inheritdoc
     */
    public function attributeLabels()
    {
        return [
            'id' => 'ID',
            'parent_id' => 'Parent ID',
            'name' => 'Name',
            'keywords' => 'Keywords',
            'description' => 'Description',
        ];
    }
    
    public function behaviors()
    {
        return [
            'image' => [
                'class' => 'rico\yii2images\behaviors\ImageBehave',
            ]
        ];
    }
    
}

controllers/CartController.php
<?php
namespace app\controllers;
use app\controllers\AppController;
use app\models\Category;
use app\models\Product;
use app\models\Cart;
use app\models\Order;
use app\models\OrderItems;
use Yii;
use yii\data\Pagination;
use yii\web\HttpException;

class CartController extends  AppController {
    
    public function actionAdd() {
        $id = Yii::$app->request->get('id');
        $qty = (int)Yii::$app->request->get('qty');
        $qty = !$qty ? 1 : $qty;
        //echo var_dump($id);
        $product = Product::findOne($id);
        if (empty($product)) return false;
        //echo var_dump($product);
        //echo print_r($product);
        $session = Yii::$app->session;
        $session->open();
        $cart = new Cart();
        $cart->addToCart($product, $qty);
        //echo print_r($session['cart']);
        //echo ' - qty ' .  var_dump($session['cart.qty']);
        //echo ' - sum ' .  var_dump($session['cart.sum']);
        //$session->destroy();
        $this->layout = false;        
        //return $this->renderPartial('cart-modal', compact('session'), false, true);
        //return $this->renderAjax('cart-modal', compact('session'));
        //return $this->render('cart-modal', compact('session'));  
        //return $this->render('/category/index', compact('session'));
        //exit();
        //return false;
        return $this->redirect(Yii::$app->request->referrer);
    }
    
    public function actionClear() {
        $session = Yii::$app->session;
        $session->open();
        $session->remove('cart');
        $session->remove('cart.qty');
        $session->remove('cart.sum');
        //echo print_r($session['cart']);
        //echo ' - qty ' .  var_dump($session['cart.qty']);
        //echo ' - sum ' .  var_dump($session['cart.sum']);
        //$session->destroy();
        $this->layout = false;
        //return $this->renderPartial('cart-modal', compact('session'), false, true);
        //return $this->renderAjax('cart-modal', compact('session'));
        return $this->render('cart-modal', compact('session'));
    }
    
    public function actionDelitem() {
        $id = Yii::$app->request->get('id');
        $session = Yii::$app->session;
        $session->open();
        $cart = new Cart();
        $cart->recalc($id);
        //echo print_r($session['cart']);
        //echo ' - qty ' .  var_dump($session['cart.qty']);
        //echo ' - sum ' .  var_dump($session['cart.sum']);
        //$session->destroy();
        //$this->layout = false;
        //return $this->renderPartial('cart-modal', compact('session'), false, true);
        //return $this->renderAjax('cart-modal', compact('session'));
        //return $this->render('cart-modal', compact('session'));
        return $this->redirect(Yii::$app->request->referrer);
        //return $this->actionView();
    }
    
    public function actionShow(){
        $session = Yii::$app->session;
        $session->open();
        $this->layout = false;
        return $this->render('cart-modal', compact('session'));
    }
    
    public function actionView() {
        $session = Yii::$app->session;
        $session->open();
        $order = new Order();
        if ($order->load(\Yii::$app->request->post())) {
            $order->qty = $session['cart.qty'];
            $order->sum = $session['cart.sum'];
            //echo var_dump(\Yii::$app->request->post());
            if ($order->save()) {
                $this->saveOrderItems($session['cart'], $order->id);
                \Yii::$app->session->setFlash('success', 'Ваш заказ принят.');                
                Yii::$app->mailer->compose('order', ['session' => $session])
                ->setFrom(['usernaim@mail.ru' => 'shape-shop.com']) //исходящий адрес, !соотв. настройкам мэйлера в web.php
                ->setTo($order->email)
                ->setSubject('Заказ с сайта...')                
                ->send();
                Yii::$app->mailer->compose('order', ['session' => $session])
                ->setFrom(['usernaim@mail.ru' => 'shape-shop.com']) //исходящий адрес, соотв. настройкам мэйлера в web.php
                ->setTo(\Yii::$app->params['adminEmail'])//адрес доставки, соотв. настройкам в params.php
                ->setSubject('Заказ с сайта...')
                ->send();
                $session->remove('cart');
                $session->remove('cart.qty');
                $session->remove('cart.sum');
                return $this->refresh();
            }
            else  {
                \Yii::$app->session->setFlash('error', 'Ошибка оформления.');
            }
        }
        $this->setMeta('Shape Shop - одежда для активных', 'Тест ключевиков корзины', 'Тест описания корзины');
        return $this->render('view', compact('session', 'order'));
    }
    
    protected function saveOrderItems($items, $order_id) {
        foreach ($items as $id => $item) {
            $order_items = new OrderItems();
            $order_items->order_id = $order_id;
            $order_items->product_id = $id;
            $order_items->name = $item['name'];
            $order_items->price = $item['price'];
            $order_items->qty_item = $item['qty'];
            $order_items->sum_item = $item['qty'] * $item['price'];
            $order_items->save();
        }
    }
}

controllers/CategoryController.php
<?php
namespace app\controllers;
use app\controllers\AppController;
use app\models\Category;
use app\models\Product;
use Yii;
use yii\data\Pagination;
use yii\web\HttpException;

class CategoryController extends  AppController {
    public function actionIndex() {
        $sale = Product::find()->where(['sale' => '1'])->limit(8)->all();
        $new = Product::find()->where(['new' => '1'])->limit(1)->all();
        $hit = Product::find()->where(['hit' => '1'])->limit(1)->all();
        //echo print_r($sale, true);
        $this->setMeta('Shape Shop - одежда для активных', 'Тест общих ключевиков', 'Тест общего описания');
        return $this->render('index', compact('sale', 'new', 'hit'));
    }
    
    public function actionView($id) {
        //$id = Yii::$app->request->get('id');
        $category = Category::findOne($id);
        if (empty($category))
            throw new HttpException(404, 'Такой категории не существует');
        //echo var_dump($id);
        //$products = Product::find()->where(['category_id' => $id])->limit(12000)->all();
        $query = Product::find()->where(['category_id' => $id]);
        $pages = new Pagination(['totalCount' => $query->count(), 'pageSize' => 8, 'forcePageParam' => false, 'pageSizeParam' => false]);
        $products = $query->offset($pages->offset)->limit($pages->limit)->all();
        
        //echo var_dump($products);
        if( count($category) > 0): ;
        $this->setMeta('Shape Shop |' . $category->name, $category->keywords, $category->description);
        else:
        $this->setMeta('Shape Shop - одежда для активных', 'Тест общих ключевиков', 'Тест общего описания');
        endif;
        return $this->render('view', compact('products', 'category', 'pages'));
    }
    
    public function actionSearch() {
        $searh = trim(Yii::$app->request->get('searh'));
        $query = Product::find()->where(['like', 'name', $searh]);
        $pages = new Pagination(['totalCount' => $query->count(), 'pageSize' => 8, 'forcePageParam' => false, 'pageSizeParam' => false]);
        $products = $query->offset($pages->offset)->limit($pages->limit)->all();
        //echo var_dump($products);
        $this->setMeta('Shape Shop - одежда для активных', 'Тест общих ключевиков', 'Тест общего описания');
        return $this->render('search', compact('products', 'category', 'searh', 'pages'));
    }
}

controllers/ProductController.php
<?php
namespace app\controllers;
use app\controllers\AppController;
use app\models\Category;
use app\models\Product;
use Yii;
use yii\web\HttpException;

class ProductController extends  AppController {
    public function actionView($id) {
        $sale = Product::find()->where(['sale' => '1'])->limit(6)->all();
        //$id = Yii::$app->request->get('id');
        //$product = Product::findOne($id);
        $product = Product::find()->with('category')->where(['id' => $id])->limit(1)->one();
        if (empty($product))
            throw new HttpException(404, 'Такой товар не существует');
        if( count($product) > 0): ;
        $this->setMeta('Shape Shop |' . $product->name, $product->keywords, $product->description);
        else:
        $this->setMeta('Shape Shop - одежда для активных', 'Тест общих ключевиков', 'Тест общего описания');
        endif;
        //$this->setMeta('Shape Shop |' . $product->name, $product->keywords, $product->description);
        return $this->render('view', compact('sale', 'product', 'category'));
}
}

views/category/index.php
<?php

/* @var $this yii\web\View */
use yii\helpers\Html;
use yii\helpers\Url;
?>
<!-- <script src="/js/cart.js"></script> -->
<!-- <script src="/js/jquery-1.11.0.min.js"></script> -->
<!-- <script type="text/javascript" src="/js/simpleCart.min.js"></script> -->
<!-- <link href="/css/memenu.css" rel="stylesheet" type="text/css" media="all" /> -->
<!-- <script type="text/javascript" src="/js/memenu.js"></script> -->
<!-- <script type="text/javascript" src="/js/move-top.js"></script> -->
<!-- <script type="text/javascript" src="/js/easing.js"></script> -->
<!-- <link href="/css/bootstrap.css" rel="stylesheet" type="text/css" media="all" /> -->

<!-- <link href="/css/style.css" rel="stylesheet" type="text/css" media="all" /> -->
  <!-- <script defer src="/js/jquery.flexslider.js"></script> -->
<!-- <link rel="stylesheet" href="/css/flexslider.css" type="text/css" media="screen" /> -->
<script>$(document).ready(function(){$(".memenu").memenu();});</script>	

<?php 
	//При переводе сайта на подгрузку картинок товара через админку (rico\yii2images) - раскомментить строки.
	//$mainImg = $product->getImage();
	//$gallery = $product->getImages();
	//$count = count($gallery);
	//$i = 0;
	?>

	<?php 
	//При переводе сайта на подгрузку картинок товара через админку (rico\yii2images) - все ссылки на картинки переписать следующим образом:
	//echo Html::img($mainImg->getUrl(), ['alt' => $product->name]) - для главной картинки
	//*****
	?>
	
	<?php 
	//Для галереи следующие 10 строк:
	//foreach ($gallery as $img):
	//if($i % 4 == 0): 
	?>
	<div class = "item <?php //if ($i == 0) echo 'active'?>">
	 <?php //endif;?>
	 <?php // Здесь вывод src через echo Html::img($mainImg->getUrl(), ['alt' => $product->name]).?>
	 <?php //if ($i % 4 == 0): ?>	 
	 <?php //endif;?>
	 <?php //endforeach;?>
	   </div>

		<!--banner-starts-->
		<?php //echo print_r($sale, true);?>
		<div class="bnr" id="home">
		<div  id="top" class="callbacks_container">
			<ul class="rslides" id="slider4">
			    <li>
					<div class="banner-1"></div>
				</li>
				<li>
					<div class="banner-2"></div>
				</li>
				<li>
					<div class="banner-3"></div>
				</li>
			</ul>
		</div>
		<div class="clearfix"> </div>
	</div>
	<!--banner-ends--> 
	<!--Slider-Starts-Here-->
				<!-- <script src="js/responsiveslides.min.js"></script> -->
			 <script>
			    // You can also use "$(window).load(function() {"
			    $(function () {
			      // Slideshow 4
			      $("#slider4").responsiveSlides({
			        auto: true,
			        pager: true,
			        nav: false,
			        speed: 500,
			        namespace: "callbacks",
			        before: function () {
			          $('.events').append("<li>before event fired.</li>");
			        },
			        after: function () {
			          $('.events').append("<li>after event fired.</li>");
			        }
			      });
			
			    });
			  </script>
			<!--End-slider-script-->
	<!--start-banner-bottom--> 	
	<div class="banner-bottom">
		<div class="container">
			<div class="banner-bottom-top">
			<?php if( !empty('$new') ): ?>
			<?php foreach ($new as $new1): ?>
				<div class="col-md-6 banner-bottom-left">
					<div class="bnr-one">
						<div class="bnr-left">
							<h1><a href="<?php echo Url::to(['product/view', 'id' => $new1->id])?>"><?php echo $new1->name ?></a></h1>
							<p><?php echo $new1->description ?></p>
							<div class="b-btn"> 
								<a href="<?php echo Url::to(['product/view', 'id' => $new1->id])?>">Новинка!</a>
							</div>
						</div>
						<div class="bnr-right"> 
							<a href="<?php echo Url::to(['product/view', 'id' => $new1->id])?>"><?= Html::img("@web/images/light-{$new1->img}", ['alt' => $new1->name]) ?></a>
						</div>
						<div class="clearfix"> </div>
					</div>
				</div>
				<?php endforeach; ?>
				<?php endif;?>
				<?php if( !empty('$hit') ): ?>
			    <?php foreach ($hit as $hit1): ?>
				<div class="col-md-6 banner-bottom-right">
					<div class="bnr-two">
						<div class="bnr-left">
							<h2><a href="<?php echo Url::to(['product/view', 'id' => $hit1->id])?>"><?php echo $hit1->name ?></a></h2>
							<p><?php echo $hit1->description ?></p>
							<div class="b-btn"> 
								<a href="<?php echo Url::to(['product/view', 'id' => $hit1->id])?>">Хит продаж!</a>
							</div>
						</div>
						<div class="bnr-right"> 
							<a href="<?php echo Url::to(['product/view', 'id' => $hit1->id])?>"><?= Html::img("@web/images/light-{$hit1->img}", ['alt' => $hit1->name]) ?></a>
						</div>
						<div class="clearfix"> </div>
					</div>
				</div>
				<?php endforeach; ?>
				<?php endif;?>
				<div class="clearfix"> </div>				
			</div>
		</div>
	</div>	
	<!--end-banner-bottom--> 
	<!--start-shoes--> 
	<?php if( !empty('$sale') ): ?>
		<div class="shoes"> 
		<div class="container"> 
		<h7>Товары месяца</h7>
			<div class="product-one">
			<?php foreach ($sale as $sale1): ?>
				<div class="col-md-3 product-left"> 
					<div class="p-one simpleCart_shelfItem">												
							<a href="<?php echo Url::to(['product/view', 'id' => $sale1->id])?>">
								<!-- <img src="/images/shoes-1.png" alt="" /> -->
								<?= Html::img("@web/images/{$sale1->img}", ['alt' => $sale1->name]) ?>
								<div class="mask">
									<span>Узнать больше</span>
								</div>
							</a>
						<h4><?php echo $sale1->name ?></h4>
						<p><span class="item_price"><?php echo $sale1->price; ?>руб</span></p>
						<!--<p><a href="<?php echo Url::to(['cart/add', 'id' => $sale1->id]);?>" data-id="<?php echo $sale1->id;?>" class="item_add"><span class=" item_price"><?php echo $sale1->price; ?>руб</span></a></p>-->					
					</div>
					<?= Html::img("@web/images/sale.png", ['alt' => 'Распродажа', 'class' => 'sale']) ?>
				</div>
				<?php endforeach; ?>
				<div class="clearfix"> </div>
			</div>			
		</div>
	</div>
	<?php endif;?>
	<!--end-shoes-->
	<!--start-abt-shoe-->	
	<div class="abt-shoe">
		<div class="container"> 
			<div class="abt-shoe-main">
				<div class="col-md-4 abt-shoe-left">
					<div class="abt-one">
						<a href="#"><?= Html::img("@web/images/abt-1.jpg", ['alt' => 'Shape Shop']); ?></a>
						<h4><a href="single.html">Тест баннера 1</a></h4>
						<p>Тестовое описание баннера 1. </p>
					</div>
				</div>
				<div class="col-md-4 abt-shoe-left">
					<div class="abt-one">
						<a href="#"><?= Html::img("@web/images/abt-2.jpg", ['alt' => 'Shape Shop']); ?></a>
						<h4><a href="single.html">Тест баннера 2</a></h4>
						<p>Тестовое описание баннера 2. </p>
					</div>
				</div>
				<div class="col-md-4 abt-shoe-left">
					<div class="abt-one">
						<a href="#"><?= Html::img("@web/images/abt-3.jpg", ['alt' => 'Shape Shop']); ?></a>
						<h4><a href="single.html">Тест баннера 3</a></h4>
						<p>Тестовое описание баннера 3. </p>
					</div>
				</div>
				<div class="clearfix"> </div>
			</div>
		</div>
	</div>
	<!--end-abt-shoe-->

views/category/search.php
<?php

/* @var $this yii\web\View */
use yii\helpers\Html;
use yii\widgets\LinkPager;
use yii\helpers\Url;

//$this->title = 'Shape Shop - одежда для активных';
?>

<script>$(document).ready(function(){$(".memenu").memenu();});</script>	

<?php 
	//При переводе сайта на подгрузку картинок товара через админку (rico\yii2images) - раскомментить строки.
	//$mainImg = $product->getImage();
	//$gallery = $product->getImages();
	//$count = count($gallery);
	//$i = 0;
	?>

	<?php 
	//При переводе сайта на подгрузку картинок товара через админку (rico\yii2images) - все ссылки на картинки переписать следующим образом:
	//echo Html::img($mainImg->getUrl(), ['alt' => $product->name]) - для главной картинки
	//*****
	?>
	
	<?php 
	//Для галереи следующие 10 строк:
	//foreach ($gallery as $img):
	//if($i % 4 == 0): 
	?>
	<div class = "item <?php //if ($i == 0) echo 'active'?>">
	 <?php //endif;?>
	 <?php // Здесь вывод src через echo Html::img($mainImg->getUrl(), ['alt' => $product->name]).?>
	 <?php //if ($i % 4 == 0): ?>	 
	 <?php //endif;?>
	 <?php //endforeach;?>
	   </div>
	   

	<!--start-shoes--> 
	<?php //echo var_dump($products) ?>
	<?php if( count($products) > 0): ?>
		<div class="shoes"> 
		<div class="container"> 
		<h7><?php echo 'Поиск по запросу:  ' . Html::encode($searh);?></h7>
			<div class="product-one">
			<?php foreach ($products as $product): ?>
				<div class="col-md-3 product-left"> 
					<div class="p-one simpleCart_shelfItem">												
							<a href="<?php echo Url::to(['product/view', 'id' => $product->id])?>">
								<!-- <img src="/images/shoes-1.png" alt="" /> -->
								<?= Html::img("@web/images/{$product->img}", ['alt' => $product->name]) ?>
								<div class="mask">
									<span>Подробнее</span>
								</div>
							</a>
						<h4><?php echo $product->name ?></h4>
						<p><span class=" item_price"><?php echo $product->price; ?>руб</span></p>
						<!--<p><a href="<?php echo Url::to(['cart/add', 'id' => $product->id]);?>" data-id="<?php echo $product->id;?>" class="item_add"><span class=" item_price"><?php echo $product->price; ?>руб</span></a></p>-->
						<!--<p><a class="item_add" href="#"><i></i> <span class=" item_price"><?php echo $product->price ?>руб</span></a></p>-->					
					</div>
				</div>
				<?php endforeach; ?>
				<div class="clearfix"> </div>				
			</div>	
			<?php echo LinkPager::widget(['pagination' => $pages]); ?>		
		</div>
	</div>
					<?php else:?>
	                       <h7>Товары по данному запросу отсутствуют.</h7>
	<?php endif;?>
	<!--end-shoes-->
	

views/category/view.php
<?php

/* @var $this yii\web\View */
use yii\helpers\Html;
use yii\widgets\LinkPager;
use yii\helpers\Url;

//$this->title = 'Shape Shop - одежда для активных';
?>

<script>$(document).ready(function(){$(".memenu").memenu();});</script>

<?php 
	//При переводе сайта на подгрузку картинок товара через админку (rico\yii2images) - раскомментить строки.
	//$mainImg = $product->getImage();
	//$gallery = $product->getImages();
	//$count = count($gallery);
	//$i = 0;
	?>

	<?php 
	//При переводе сайта на подгрузку картинок товара через админку (rico\yii2images) - все ссылки на картинки переписать следующим образом:
	//echo Html::img($mainImg->getUrl(), ['alt' => $product->name]) - для главной картинки
	//*****
	?>
	
	<?php 
	//Для галереи следующие 10 строк:
	//foreach ($gallery as $img):
	//if($i % 4 == 0): 
	?>
	<div class = "item <?php //if ($i == 0) echo 'active'?>">
	 <?php //endif;?>
	 <?php // Здесь вывод src через echo Html::img($mainImg->getUrl(), ['alt' => $product->name]).?>
	 <?php //if ($i % 4 == 0): ?>	 
	 <?php //endif;?>
	 <?php //endforeach;?>
	   </div>
	   
	<!--start-shoes--> 
	<?php //echo var_dump($products) ?>
	<?php if( count($products) > 0): ?>
		<div class="shoes"> 
		<div class="container"> 
		<h7><?php echo $category->name;?></h7>
			<div class="product-one">
			<?php foreach ($products as $product): ?>
				<div class="col-md-3 product-left"> 
					<div class="p-one simpleCart_shelfItem">												
							<a href="<?php echo Url::to(['product/view', 'id' => $product->id])?>">
								<!-- <img src="/images/shoes-1.png" alt="" /> -->
								<?= Html::img("@web/images/{$product->img}", ['alt' => $product->name]) ?>
								<div class="mask">
									<span>Подробнее</span>
								</div>
							</a>
						<h4><?php echo $product->name ?></h4>
						<!--<p><a class="item_add" href="#"><i></i> <span class=" item_price"><?php echo $product->price ?>руб</span></a></p>-->
						<p><span class=" item_price"><?php echo $product->price; ?>руб</span></p>
						<!--<p><a href="<?php echo Url::to(['cart/add', 'id' => $product->id]);?>" data-id="<?php echo $product->id;?>" class="item_add"><span class=" item_price"><?php echo $product->price; ?>руб</span></a></p>-->					
					</div>
				</div>
				<?php endforeach; ?>
				<div class="clearfix"> </div>				
			</div>	
			<?php echo LinkPager::widget(['pagination' => $pages]); ?>		
		</div>
	</div>
					<?php else:?>
	                       <h7>Товары в данной категории отсутствуют.</h7>
	<?php endif;?>
	<!--end-shoes-->
	