models/Product.php
<?php

namespace app\models;

use Yii;

/**
 * This is the model class for table "product".
 *
 * @property int $id
 * @property int $category_id
 * @property string $name
 * @property string $content
 * @property double $price
 * @property string $keywords
 * @property string $description
 * @property string $img
 * @property string $sale
 * @property string $new
 * @property string $hit
 */
class Product extends \yii\db\ActiveRecord
{
    /**
     * @inheritdoc
     */
    public static function tableName()
    {
        return 'product';
    }
    
    public function getCategory() {
        return $this->hasOne(Category::className(), ['id' => 'category_id']);
    }

    /**
     * @inheritdoc
     */
    public function rules()
    {
        return [
            [['category_id', 'name'], 'required'],
            [['category_id'], 'integer'],
            [['content', 'sale', 'new', 'hit'], 'string'],
            [['price'], 'number'],
            [['name', 'keywords', 'description', 'img'], 'string', 'max' => 255],
        ];
    }

    /**
     * @inheritdoc
     */
    public function attributeLabels()
    {
        return [
            'id' => 'ID',
            'category_id' => 'Category ID',
            'name' => 'Name',
            'content' => 'Content',
            'price' => 'Price',
            'keywords' => 'Keywords',
            'description' => 'Description',
            'img' => 'Img',
            'sale' => 'Sale',
            'new' => 'New',
            'hit' => 'Hit',
        ];
    }
    
    public function behaviors()
    {
        return [
            'image' => [
                'class' => 'rico\yii2images\behaviors\ImageBehave',
            ]
        ];
    }
    
}

controllers/CartController.php
<?php
namespace app\controllers;
use app\controllers\AppController;
use app\models\Category;
use app\models\Product;
use app\models\Cart;
use app\models\Order;
use app\models\OrderItems;
use Yii;
use yii\data\Pagination;
use yii\web\HttpException;

class CartController extends  AppController {
    
    public function actionAdd() {
        $id = Yii::$app->request->get('id');
        $qty = (int)Yii::$app->request->get('qty');
        $qty = !$qty ? 1 : $qty;
        //echo var_dump($id);
        $product = Product::findOne($id);
        if (empty($product)) return false;
        //echo var_dump($product);
        //echo print_r($product);
        $session = Yii::$app->session;
        $session->open();
        $cart = new Cart();
        $cart->addToCart($product, $qty);
        //echo print_r($session['cart']);
        //echo ' - qty ' .  var_dump($session['cart.qty']);
        //echo ' - sum ' .  var_dump($session['cart.sum']);
        //$session->destroy();
        $this->layout = false;        
        //return $this->renderPartial('cart-modal', compact('session'), false, true);
        //return $this->renderAjax('cart-modal', compact('session'));
        //return $this->render('cart-modal', compact('session'));  
        //return $this->render('/category/index', compact('session'));
        //exit();
        //return false;
        return $this->redirect(Yii::$app->request->referrer);
    }
    
    public function actionClear() {
        $session = Yii::$app->session;
        $session->open();
        $session->remove('cart');
        $session->remove('cart.qty');
        $session->remove('cart.sum');
        //echo print_r($session['cart']);
        //echo ' - qty ' .  var_dump($session['cart.qty']);
        //echo ' - sum ' .  var_dump($session['cart.sum']);
        //$session->destroy();
        $this->layout = false;
        //return $this->renderPartial('cart-modal', compact('session'), false, true);
        //return $this->renderAjax('cart-modal', compact('session'));
        return $this->render('cart-modal', compact('session'));
    }
    
    public function actionDelitem() {
        $id = Yii::$app->request->get('id');
        $session = Yii::$app->session;
        $session->open();
        $cart = new Cart();
        $cart->recalc($id);
        //echo print_r($session['cart']);
        //echo ' - qty ' .  var_dump($session['cart.qty']);
        //echo ' - sum ' .  var_dump($session['cart.sum']);
        //$session->destroy();
        //$this->layout = false;
        //return $this->renderPartial('cart-modal', compact('session'), false, true);
        //return $this->renderAjax('cart-modal', compact('session'));
        //return $this->render('cart-modal', compact('session'));
        return $this->redirect(Yii::$app->request->referrer);
        //return $this->actionView();
    }
    
    public function actionShow(){
        $session = Yii::$app->session;
        $session->open();
        $this->layout = false;
        return $this->render('cart-modal', compact('session'));
    }
    
    public function actionView() {
        $session = Yii::$app->session;
        $session->open();
        $order = new Order();
        if ($order->load(\Yii::$app->request->post())) {
            $order->qty = $session['cart.qty'];
            $order->sum = $session['cart.sum'];
            //echo var_dump(\Yii::$app->request->post());
            if ($order->save()) {
                $this->saveOrderItems($session['cart'], $order->id);
                \Yii::$app->session->setFlash('success', 'Ваш заказ принят.');                
                Yii::$app->mailer->compose('order', ['session' => $session])
                ->setFrom(['usernaim@mail.ru' => 'shape-shop.com']) //исходящий адрес, !соотв. настройкам мэйлера в web.php
                ->setTo($order->email)
                ->setSubject('Заказ с сайта...')                
                ->send();
                Yii::$app->mailer->compose('order', ['session' => $session])
                ->setFrom(['usernaim@mail.ru' => 'shape-shop.com']) //исходящий адрес, соотв. настройкам мэйлера в web.php
                ->setTo(\Yii::$app->params['adminEmail'])//адрес доставки, соотв. настройкам в params.php
                ->setSubject('Заказ с сайта...')
                ->send();
                $session->remove('cart');
                $session->remove('cart.qty');
                $session->remove('cart.sum');
                return $this->refresh();
            }
            else  {
                \Yii::$app->session->setFlash('error', 'Ошибка оформления.');
            }
        }
        $this->setMeta('Shape Shop - одежда для активных', 'Тест ключевиков корзины', 'Тест описания корзины');
        return $this->render('view', compact('session', 'order'));
    }
    
    protected function saveOrderItems($items, $order_id) {
        foreach ($items as $id => $item) {
            $order_items = new OrderItems();
            $order_items->order_id = $order_id;
            $order_items->product_id = $id;
            $order_items->name = $item['name'];
            $order_items->price = $item['price'];
            $order_items->qty_item = $item['qty'];
            $order_items->sum_item = $item['qty'] * $item['price'];
            $order_items->save();
        }
    }
}

controllers/CategoryController.php
<?php
namespace app\controllers;
use app\controllers\AppController;
use app\models\Category;
use app\models\Product;
use Yii;
use yii\data\Pagination;
use yii\web\HttpException;

class CategoryController extends  AppController {
    public function actionIndex() {
        $sale = Product::find()->where(['sale' => '1'])->limit(8)->all();
        $new = Product::find()->where(['new' => '1'])->limit(1)->all();
        $hit = Product::find()->where(['hit' => '1'])->limit(1)->all();
        //echo print_r($sale, true);
        $this->setMeta('Shape Shop - одежда для активных', 'Тест общих ключевиков', 'Тест общего описания');
        return $this->render('index', compact('sale', 'new', 'hit'));
    }
    
    public function actionView($id) {
        //$id = Yii::$app->request->get('id');
        $category = Category::findOne($id);
        if (empty($category))
            throw new HttpException(404, 'Такой категории не существует');
        //echo var_dump($id);
        //$products = Product::find()->where(['category_id' => $id])->limit(12000)->all();
        $query = Product::find()->where(['category_id' => $id]);
        $pages = new Pagination(['totalCount' => $query->count(), 'pageSize' => 8, 'forcePageParam' => false, 'pageSizeParam' => false]);
        $products = $query->offset($pages->offset)->limit($pages->limit)->all();
        
        //echo var_dump($products);
        if( count($category) > 0): ;
        $this->setMeta('Shape Shop |' . $category->name, $category->keywords, $category->description);
        else:
        $this->setMeta('Shape Shop - одежда для активных', 'Тест общих ключевиков', 'Тест общего описания');
        endif;
        return $this->render('view', compact('products', 'category', 'pages'));
    }
    
    public function actionSearch() {
        $searh = trim(Yii::$app->request->get('searh'));
        $query = Product::find()->where(['like', 'name', $searh]);
        $pages = new Pagination(['totalCount' => $query->count(), 'pageSize' => 8, 'forcePageParam' => false, 'pageSizeParam' => false]);
        $products = $query->offset($pages->offset)->limit($pages->limit)->all();
        //echo var_dump($products);
        $this->setMeta('Shape Shop - одежда для активных', 'Тест общих ключевиков', 'Тест общего описания');
        return $this->render('search', compact('products', 'category', 'searh', 'pages'));
    }
}

controllers/ProductController.php
<?php
namespace app\controllers;
use app\controllers\AppController;
use app\models\Category;
use app\models\Product;
use Yii;
use yii\web\HttpException;

class ProductController extends  AppController {
    public function actionView($id) {
        $sale = Product::find()->where(['sale' => '1'])->limit(6)->all();
        //$id = Yii::$app->request->get('id');
        //$product = Product::findOne($id);
        $product = Product::find()->with('category')->where(['id' => $id])->limit(1)->one();
        if (empty($product))
            throw new HttpException(404, 'Такой товар не существует');
        if( count($product) > 0): ;
        $this->setMeta('Shape Shop |' . $product->name, $product->keywords, $product->description);
        else:
        $this->setMeta('Shape Shop - одежда для активных', 'Тест общих ключевиков', 'Тест общего описания');
        endif;
        //$this->setMeta('Shape Shop |' . $product->name, $product->keywords, $product->description);
        return $this->render('view', compact('sale', 'product', 'category'));
}
}

views/product/view.php
<?php
/* @var $this yii\web\View */
use yii\helpers\Html;
use yii\widgets\LinkPager;
use yii\helpers\Url;

//$this->title = 'Shape Shop - одежда для активных';
?>

<script>$(document).ready(function(){$(".memenu").memenu();});</script>	

	<?php //echo var_dump($product->category); ?>
	<?php //echo print_r($product); ?>
	
	
	<?php 
	//При переводе сайта на подгрузку картинок товара через админку (rico\yii2images) - раскомментить строки.
	//$mainImg = $product->getImage();
	//$gallery = $product->getImages();
	//$count = count($gallery);
	//$i = 0;
	?>

	<?php 
	//При переводе сайта на подгрузку картинок товара через админку (rico\yii2images) - все ссылки на картинки переписать следующим образом:
	//echo Html::img($mainImg->getUrl(), ['alt' => $product->name]) - для главной картинки
	//*****
	?>
	
	<?php 
	//Для галереи следующие 10 строк:
	//foreach ($gallery as $img):
	//if($i % 4 == 0): 
	?>
	<div class = "item <?php //if ($i == 0) echo 'active'?>">
	 <?php //endif;?>
	 <?php // Здесь вывод src через echo Html::img($mainImg->getUrl(), ['alt' => $product->name]).?>
	 <?php //if ($i % 4 == 0): ?>	 
	 <?php //endif;?>
	 <?php //endforeach;?>
	   </div>
	

<!--start-breadcrumbs-->
<?php if( count($product) > 0): ?>
	<div class="breadcrumbs">
		<div class="container">
			<div class="breadcrumbs-main">
				<ol class="breadcrumb">
					<li><a href="<?php echo Url::home();?>">Главная</a></li>
					<li class="active"><a href="<?php echo Url::to(['category/view', 'id' => $product->category->id])?>"> <?php echo $product->category->name;?></a></li>
				</ol>
			</div>
		</div>
	</div>
	<?php endif;?>
	<!--end-breadcrumbs-->
	<!--start-single-->
	<?php if( count($product) > 0): ?>
	<div class="single contact">
		<div class="container">
			<div class="single-main">
				<div class="col-md-9 single-main-left">
				<div class="sngl-top">
					<div class="col-md-5 single-top-left">	
						<div class="flexslider">
							<ul class="slides">								
								<li data-thumb="<?php echo "/images/s1-" . "{$product->img}" ; ?>">
									<?= Html::img("@web/images/s1-{$product->img}", ['alt' => $product->name]) ?>
								</li>
								<li data-thumb="<?php echo "/images/s2-" . "{$product->img}" ; ?>">
									<?= Html::img("@web/images/s2-{$product->img}", ['alt' => $product->name]) ?>
								</li>
								<li data-thumb="<?php echo "/images/s3-" . "{$product->img}" ; ?>">
									<?= Html::img("@web/images/s3-{$product->img}", ['alt' => $product->name]) ?>
								</li>
								<li data-thumb="<?php echo "/images/s4-" . "{$product->img}" ; ?>">
									<?= Html::img("@web/images/s4-{$product->img}", ['alt' => $product->name]) ?>
								</li>
							</ul>
						</div>
<!-- FlexSlider --> 

	<script>
// Can also be used with $(document).ready()
$(window).load(function() {
  $('.flexslider').flexslider({
    animation: "slide",
    controlNav: "thumbnails"
  });
});
</script>
				</div>	
				
				<div class="col-md-7 single-top-right">
					<div class="details-left-info simpleCart_shelfItem">
					<?php if( count($product) > 0): ?>
						<h3><?php echo $product->name;?></h3>
						<p class="availability"><a href="<?php echo Url::to(['category/view', 'id' => $product->category->id])?>"> <?php echo "Категория:  " . $product->category->name;?></a></p>
						<p class="availability"><?php echo $product->description;?></p>
						<div class="price_single">
							<span class="reducedfrom"><?php echo $product->price*2 ?>руб</span>
							<span class="actual item_price"><?php echo $product->price ?>руб</span><!-- <a href="#">Добавить в корзину</a> -->
						</div>
						<h2 class="quick">Характеристики:</h2>
						<p class="quick_desc"><?php echo $product->content;?></p>
						<div class="quantity_box">
						<!-- <span>Количество:</span>
						<input type="text" value="5" id="qty" size="5" name="qty"/> -->
							<!-- <ul class="product-qty" id="qty">
								<span>Количество:</span>
								<select>
									<option>1</option>
									<option>2</option>
									<option>3</option>
									<option>4</option>
									<option>5</option>
									<option>6</option>
								</select>
							</ul> -->
						</div>
					<div class="clearfix"> </div>
				<div class="b-btn">
				         <a class="item_add" href="<?php echo Url::to(['cart/add', 'id' => $product->id]);?>" data-id="<?php echo $product->id;?>">В корзину</a>
				</div>
						<?php else:?>
	                       <h7>Товар отсутствуeт.</h7>
	<?php endif;?>
			</div>
		</div>

		<div class="clearfix"></div>
	</div>
	<?php if( !empty('$sale') ): ?>
					<div class="latest products">
					<h7>Товары месяца</h7>
						<div class="product-one">
						<?php foreach ($sale as $sale1): ?>
							<div class="col-md-4 product-left single-left"> 
								<div class="p-one simpleCart_shelfItem">
									
									<a href="<?php echo Url::to(['product/view', 'id' => $sale1->id])?>">
								<!-- <img src="/images/shoes-1.png" alt="" /> -->
								<?= Html::img("@web/images/{$sale1->img}", ['alt' => $sale1->name]) ?>
								<div class="mask">
									<span>Узнать больше</span>
								</div>
							</a>
							<h4><?php echo $sale1->name ?></h4>
							<p><span class="item_price"><?php echo $sale1->price; ?>руб</span></p>
						<!--<p><a href="<?php echo Url::to(['cart/add', 'id' => $sale1->id]);?>" data-id="<?php echo $sale1->id;?>" class="item_add"><span class=" item_price"><?php echo $sale1->price; ?>руб</span></a></p>-->
						    <!--<p><a class="item_add" href="#"><i></i> <span class=" item_price"><?php echo $sale1->price ?>руб</span></a></p>-->	
									
								</div>
								<?= Html::img("@web/images/sale.png", ['alt' => 'Распродажа', 'class' => 'sale']) ?>
							</div>
							<?php endforeach; ?>							
							<div class="clearfix"> </div>
						</div>
					</div>
					<?php endif;?>
				</div>
				<div class="col-md-3 single-right">
					<h3>Реклама</h3>
					<ul class="product-categories">
                        <?= Html::img("@web/images/shipping.jpg", ['alt' => 'Shape Shop']); ?>
					</ul>
					<h3>Реклама</h3>
					<ul class="product-categories">
                        <?= Html::img("@web/images/shipping.jpg", ['alt' => 'Shape Shop']); ?>
					</ul>
					<h3>Реклама</h3>
					<ul class="product-categories">
                        <?= Html::img("@web/images/shipping.jpg", ['alt' => 'Shape Shop']); ?>
					</ul>
				</div>
				<div class="clearfix"> </div>
			</div>
		</div>
	</div>
	<?php endif;?>
	<!--end-single<?php echo Url::to(['cart/add', 'id' => $product->id]);?>-->