models/Cart.php
<?php
namespace app\models;

use Yii;

class Cart extends \yii\db\ActiveRecord {
    public function addToCart($product, $qty = 1) {
        //echo '111';
        if (isset($_SESSION['cart'][$product->id])) {
            $_SESSION['cart'][$product->id]['qty'] += $qty;
        }
            else {
                $_SESSION['cart'][$product->id] = [
                    'qty' => $qty,
                    'name' => $product->name,
                    'price' => $product->price,
                    'img' => $product->img
                ];
            }
            if (isset($_SESSION['cart.qty'])) {
                $_SESSION['cart.qty'] = $_SESSION['cart.qty'] + $qty;}
                else {$_SESSION['cart.qty'] = $qty;
            };
            
            if (isset($_SESSION['cart.sum'])) {
                $_SESSION['cart.sum'] = $_SESSION['cart.sum'] + $qty * $product->price;}
                else {$_SESSION['cart.sum'] = $qty * $product->price;
                };
            
            //$_SESSION['cart.qty'] = isset($_SESSION['cart.qty']) ? $_SESSION['cart.qty'] + $qty : $qty;
            //$_SESSION['cart.sum'] = isset($_SESSION['cart.sum']) ? $_SESSION['cart.sum'] + $qty * $product->price : $qty * $product->price;
        }
        
        public function recalc($id) {
            if (!isset($_SESSION['cart'][$id])) return FALSE;
            $qtyMinus = $_SESSION['cart'][$id]['qty'];
            $sumMinus = $_SESSION['cart'][$id]['qty'] * $_SESSION['cart'][$id]['price'];
            $_SESSION['cart.qty'] -= $qtyMinus;
            $_SESSION['cart.sum'] -= $sumMinus;
            unset($_SESSION['cart'][$id]);
        }
        
        public function behaviors()
        {
            return [
                'image' => [
                    'class' => 'rico\yii2images\behaviors\ImageBehave',
                ]
            ];
        }
        
    }

controllers/CartController.php
<?php
namespace app\controllers;
use app\controllers\AppController;
use app\models\Category;
use app\models\Product;
use app\models\Cart;
use app\models\Order;
use app\models\OrderItems;
use Yii;
use yii\data\Pagination;
use yii\web\HttpException;

class CartController extends  AppController {
    
    public function actionAdd() {
        $id = Yii::$app->request->get('id');
        $qty = (int)Yii::$app->request->get('qty');
        $qty = !$qty ? 1 : $qty;
        //echo var_dump($id);
        $product = Product::findOne($id);
        if (empty($product)) return false;
        //echo var_dump($product);
        //echo print_r($product);
        $session = Yii::$app->session;
        $session->open();
        $cart = new Cart();
        $cart->addToCart($product, $qty);
        //echo print_r($session['cart']);
        //echo ' - qty ' .  var_dump($session['cart.qty']);
        //echo ' - sum ' .  var_dump($session['cart.sum']);
        //$session->destroy();
        $this->layout = false;        
        //return $this->renderPartial('cart-modal', compact('session'), false, true);
        //return $this->renderAjax('cart-modal', compact('session'));
        //return $this->render('cart-modal', compact('session'));  
        //return $this->render('/category/index', compact('session'));
        //exit();
        //return false;
        return $this->redirect(Yii::$app->request->referrer);
    }
    
    public function actionClear() {
        $session = Yii::$app->session;
        $session->open();
        $session->remove('cart');
        $session->remove('cart.qty');
        $session->remove('cart.sum');
        //echo print_r($session['cart']);
        //echo ' - qty ' .  var_dump($session['cart.qty']);
        //echo ' - sum ' .  var_dump($session['cart.sum']);
        //$session->destroy();
        $this->layout = false;
        //return $this->renderPartial('cart-modal', compact('session'), false, true);
        //return $this->renderAjax('cart-modal', compact('session'));
        return $this->render('cart-modal', compact('session'));
    }
    
    public function actionDelitem() {
        $id = Yii::$app->request->get('id');
        $session = Yii::$app->session;
        $session->open();
        $cart = new Cart();
        $cart->recalc($id);
        //echo print_r($session['cart']);
        //echo ' - qty ' .  var_dump($session['cart.qty']);
        //echo ' - sum ' .  var_dump($session['cart.sum']);
        //$session->destroy();
        //$this->layout = false;
        //return $this->renderPartial('cart-modal', compact('session'), false, true);
        //return $this->renderAjax('cart-modal', compact('session'));
        //return $this->render('cart-modal', compact('session'));
        return $this->redirect(Yii::$app->request->referrer);
        //return $this->actionView();
    }
    
    public function actionShow(){
        $session = Yii::$app->session;
        $session->open();
        $this->layout = false;
        return $this->render('cart-modal', compact('session'));
    }
    
    public function actionView() {
        $session = Yii::$app->session;
        $session->open();
        $order = new Order();
        if ($order->load(\Yii::$app->request->post())) {
            $order->qty = $session['cart.qty'];
            $order->sum = $session['cart.sum'];
            //echo var_dump(\Yii::$app->request->post());
            if ($order->save()) {
                $this->saveOrderItems($session['cart'], $order->id);
                \Yii::$app->session->setFlash('success', 'Ваш заказ принят.');                
                Yii::$app->mailer->compose('order', ['session' => $session])
                ->setFrom(['usernaim@mail.ru' => 'shape-shop.com']) //исходящий адрес, !соотв. настройкам мэйлера в web.php
                ->setTo($order->email)
                ->setSubject('Заказ с сайта...')                
                ->send();
                Yii::$app->mailer->compose('order', ['session' => $session])
                ->setFrom(['usernaim@mail.ru' => 'shape-shop.com']) //исходящий адрес, соотв. настройкам мэйлера в web.php
                ->setTo(\Yii::$app->params['adminEmail'])//адрес доставки, соотв. настройкам в params.php
                ->setSubject('Заказ с сайта...')
                ->send();
                $session->remove('cart');
                $session->remove('cart.qty');
                $session->remove('cart.sum');
                return $this->refresh();
            }
            else  {
                \Yii::$app->session->setFlash('error', 'Ошибка оформления.');
            }
        }
        $this->setMeta('Shape Shop - одежда для активных', 'Тест ключевиков корзины', 'Тест описания корзины');
        return $this->render('view', compact('session', 'order'));
    }
    
    protected function saveOrderItems($items, $order_id) {
        foreach ($items as $id => $item) {
            $order_items = new OrderItems();
            $order_items->order_id = $order_id;
            $order_items->product_id = $id;
            $order_items->name = $item['name'];
            $order_items->price = $item['price'];
            $order_items->qty_item = $item['qty'];
            $order_items->sum_item = $item['qty'] * $item['price'];
            $order_items->save();
        }
    }
}

controllers/ProductController.php
<?php
namespace app\controllers;
use app\controllers\AppController;
use app\models\Category;
use app\models\Product;
use Yii;
use yii\web\HttpException;

class ProductController extends  AppController {
    public function actionView($id) {
        $sale = Product::find()->where(['sale' => '1'])->limit(6)->all();
        //$id = Yii::$app->request->get('id');
        //$product = Product::findOne($id);
        $product = Product::find()->with('category')->where(['id' => $id])->limit(1)->one();
        if (empty($product))
            throw new HttpException(404, 'Такой товар не существует');
        if( count($product) > 0): ;
        $this->setMeta('Shape Shop |' . $product->name, $product->keywords, $product->description);
        else:
        $this->setMeta('Shape Shop - одежда для активных', 'Тест общих ключевиков', 'Тест общего описания');
        endif;
        //$this->setMeta('Shape Shop |' . $product->name, $product->keywords, $product->description);
        return $this->render('view', compact('sale', 'product', 'category'));
}
}

views/cart/cart-modal.php
<?php

/* @var $this yii\web\View */
use yii\helpers\Html;
use yii\helpers\Url;
?>

<?php if (!empty($session['cart'])): ?>
<div class="table-responsive">
	<table class="table table-striped">
		<thead>
			<tr>
				<th>Фото</th>
				<th>Наименование</th>
				<th>Кол-во</th>
				<th>Цена</th>				
			</tr>
		</thead>
		<tbody>
<?php foreach ($session['cart'] as $id => $item):?>
            <tr>
				<td><?php  echo Html::img("@web/images/{$item['img']}", ['alt' => $item['name'], 'height' => 50])?></td>
				<td><?php  echo $item['name']?></td>
				<td><?php  echo $item['qty']?></td>
				<td><?php  echo $item['price']?></td>				
			</tr>
<?php endforeach;?>
<tr>
				<td colspan="3">Итого:</td>
				<td><?php echo $session['cart.qty']?>
</td>
<tr>
				<td colspan="3">Сумма:</td>
				<td><?php echo $session['cart.sum']?>
</td>
		
		</tbody>
	</table>
</div>
<?php else :?>
<h3>Корзина пуста.</h3>
<?php endif;?>

views/cart/view.php
<?php
use yii\helpers\Html;
use yii\helpers\Url;
use \yii\db\ActiveRecord; 
use yii\widgets\ActiveForm;
?>

<div class="container">
<?php if (Yii::$app->session->hasFlash('success')):?>
<div class="alert alert-success alert-dismissible" role="alert">
<button type="button" class="close" data-dismiss="alert" aria-label="close"><span aria-hidden="true">&times;</span></button>
<?php echo Yii::$app->session->getFlash('success');?>
</div>
<?php endif; ?>
<?php if (Yii::$app->session->hasFlash('error')):?>
<div class="alert alert-danger alert-dismissible" role="alert">
<button type="button" class="close" data-dismiss="alert" aria-label="close"><span aria-hidden="true">&times;</span></button>
<?php echo Yii::$app->session->getFlash('error');?>
</div>
<?php endif; ?>
<?php if (!empty($session['cart'])): ?>
<div class="table-responsive">
	<table class="table table-striped">
		<thead>
			<tr>
				<th>Фото</th>
				<th>Наименование</th>
				<th>Кол-во</th>
				<th>Цена</th>
				<th><span class="glyphicon glyphicon-remove" aria-hidden="true"></span></th>
			</tr>
		</thead>
		<tbody>
<?php foreach ($session['cart'] as $id => $item):?>
            <tr>
				<td><?php  echo Html::img("@web/images/{$item['img']}", ['alt' => $item['name'], 'height' => 50])?></td>
				<td><a href="<?php echo Url::to(['product/view', 'id' => $id])?>"><?php  echo $item['name']?></a></td>
				<td><?php  echo $item['qty']?></td>
				<td><?php  echo $item['price']?></td>
				<td><div><a class="glyphicon glyphicon-remove text-danger del-item" aria-hidden="true" href="<?php echo Url::to(['cart/delitem', 'id' => $id])?>"><span data-id="<?php echo $id?>"></span></a></div></td>				
				<!-- <td><div><a class="glyphicon glyphicon-remove text-danger del-item" aria-hidden="true" href="" onclick="return delItem()"><span data-id="<?php echo $id?>"></span></a></div></td> -->
			</tr>
<?php endforeach;?>
<tr>
				<td colspan="4">Итого:</td>
				<td><?php echo $session['cart.qty']?>
</td>
<tr>
				<td colspan="4">Сумма:</td>
				<td><?php echo $session['cart.sum']?>
</td>
		
		</tbody>
	</table>
</div>
<hr/>
<?php $form = ActiveForm::begin()?>
<?php echo $form->field($order, 'name');?>
<?php echo $form->field($order, 'email');?>
<?php echo $form->field($order, 'phone');?>
<?php echo $form->field($order, 'address');?>
<?php echo Html::submitButton('Заказать', ['class' => 'btn btn-success'])?>
<?php ActiveForm::end()?>
<?php else :?>
<h3>Корзина пуста.</h3>
<?php endif;?>
</div>